import type { Product } from '../types';

export const SEED_PRODUCTS: Product[] = [
  // ==================== MEN'S COLLECTION (24 items) ====================
  {
    id: 'men-001',
    name: 'Raw Mulberry Silk Bandhgala Jacket',
    price: 8899,
    stock: 14,
    gender: 'men',
    category: 'jackets',
    subcategory: 'bandhgala',
    sizes: ['38', '40', '42', '44'],
    colors: ['Oatmeal Ecru', 'Obsidian Black', 'Burnt Terracotta'],
    rating: 4.9,
    reviewCount: 42,
    imageUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1000&q=85',
    description: 'Sculptural structured bandhgala tailored from handloom Bhagalpur mulberry raw silk with antique horn buttons and tonal french seams.',
    material: 'Raw Mulberry Silk',
    occasion: 'wedding, formal, festive',
    styleTags: ['regal', 'luxury', 'tailored', 'structured'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'men-002',
    name: 'Hand-Spun Khadi Linen Kurta',
    price: 4899,
    stock: 28,
    gender: 'men',
    category: 'kurtas',
    subcategory: 'kurta',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Chalk White', 'Sage Green', 'Indigo Ash'],
    rating: 4.8,
    reviewCount: 56,
    imageUrl: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=1000&q=85',
    description: 'Relaxed drop-shoulder tunic woven on traditional wooden pit looms from certified organic Khadi cotton and long-staple linen.',
    material: 'Khadi Linen Cotton',
    occasion: 'casual, summer, festive, vacation',
    styleTags: ['minimal', 'artisanal', 'breathable', 'relaxed'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'men-003',
    name: 'Tailored Poplin Formal Shirt',
    price: 3499,
    stock: 35,
    gender: 'men',
    category: 'formal shirts',
    subcategory: 'formal shirt',
    sizes: ['38', '39', '40', '42', '44'],
    colors: ['Crisp White', 'Sky Blue', 'Ecru Mist', 'Sage Green'],
    rating: 4.7,
    reviewCount: 68,
    imageUrl: 'https://images.unsplash.com/photo-1620012253295-c15c429fccf8?auto=format&fit=crop&w=1000&q=85',
    description: 'Crisp 120s two-ply Egyptian cotton formal shirt featuring a semi-spread collar, mother-of-pearl buttons, and tailored cuffs.',
    material: 'Egyptian Cotton Poplin',
    occasion: 'office, formal, interview, dinner',
    styleTags: ['classic', 'tailored', 'crisp', 'formal'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'men-004',
    name: 'Breathable Irish Linen Casual Shirt',
    price: 3899,
    stock: 22,
    gender: 'men',
    category: 'linen shirts',
    subcategory: 'linen shirt',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Warm Sand', 'Olive Leaf', 'Washed Rose'],
    rating: 4.9,
    reviewCount: 39,
    imageUrl: 'https://images.unsplash.com/photo-1589310243389-96a5483213a8?auto=format&fit=crop&w=1000&q=85',
    description: 'Pure certified European flax linen shirt with an open camp collar, airy loose weave, and effortless warm-weather drape.',
    material: 'European Flax Linen',
    occasion: 'summer, vacation, casual, resort',
    styleTags: ['airy', 'resort', 'relaxed', 'breathable'],
    isNew: true,
    isArchived: false,
  },
  {
    id: 'men-005',
    name: 'Brushed Cotton Flannel Casual Shirt',
    price: 2999,
    stock: 19,
    gender: 'men',
    category: 'casual shirts',
    subcategory: 'casual shirt',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Cedar Check', 'Charcoal Heather', 'Forest Sage'],
    rating: 4.6,
    reviewCount: 31,
    imageUrl: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=1000&q=85',
    description: 'Ultra-soft double-brushed organic cotton flannel casual shirt for versatile autumn and winter layering.',
    material: 'Brushed Organic Cotton',
    occasion: 'casual, travel, dinner',
    styleTags: ['soft', 'cozy', 'relaxed', 'autumn'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'men-006',
    name: 'Heavyweight Supima Cotton T-Shirt',
    price: 1899,
    stock: 45,
    gender: 'men',
    category: 't-shirts',
    subcategory: 't-shirt',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Bone White', 'Espresso Brown', 'Sage Moss', 'Obsidian Black'],
    rating: 4.8,
    reviewCount: 94,
    imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1000&q=85',
    description: '260 GSM heavyweight American Supima cotton t-shirt with a structured boxy drape and reinforced ribbed neck collar.',
    material: 'Heavyweight Supima Cotton',
    occasion: 'casual, everyday, lounge',
    styleTags: ['minimal', 'structured', 'durable', 'everyday'],
    isNew: true,
    isArchived: false,
  },
  {
    id: 'men-007',
    name: 'Japanese Selvedge Raw Denim Jeans',
    price: 6499,
    stock: 18,
    gender: 'men',
    category: 'jeans',
    subcategory: 'jeans',
    sizes: ['30', '32', '34', '36'],
    colors: ['Raw Indigo', 'Faded Stone Black'],
    rating: 4.9,
    reviewCount: 47,
    imageUrl: 'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=1000&q=85',
    description: '13.5 oz shuttle-loom woven Japanese selvedge denim with natural indigo vat dye, copper rivets, and a straight leg cut.',
    material: 'Japanese Selvedge Denim',
    occasion: 'casual, weekend, travel',
    styleTags: ['heritage', 'artisanal', 'straight leg', 'raw'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'men-008',
    name: 'Pleated Tapered Cotton Chinos',
    price: 3699,
    stock: 26,
    gender: 'men',
    category: 'chinos',
    subcategory: 'trousers',
    sizes: ['30', '32', '34', '36', '38'],
    colors: ['Warm Khaki', 'Slate Gray', 'Dark Olive'],
    rating: 4.7,
    reviewCount: 52,
    imageUrl: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=1000&q=85',
    description: 'High-waisted double-pleated tailored chinos woven from stretch long-staple cotton twill with an elegant tapered ankle break.',
    material: 'Cotton Twill',
    occasion: 'office, formal, casual, dinner',
    styleTags: ['tailored', 'pleated', 'smart casual', 'versatile'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'men-009',
    name: 'Fermented Indigo Artisan Bomber Jacket',
    price: 9499,
    stock: 12,
    gender: 'men',
    category: 'jackets',
    subcategory: 'bomber jacket',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Natural Indigo', 'Charcoal Washed'],
    rating: 5.0,
    reviewCount: 28,
    imageUrl: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=1000&q=85',
    description: 'Handcrafted bomber jacket dipped 12 times in living fermented organic indigo vats with heavyweight brass hardware.',
    material: 'Natural Indigo Handloom Cotton',
    occasion: 'evening, casual, party',
    styleTags: ['artisanal', 'statement', 'modern luxury', 'indigo'],
    isNew: true,
    isArchived: false,
  },
  {
    id: 'men-010',
    name: 'Minimal Italian Nappa Leather Loafers',
    price: 8999,
    stock: 15,
    gender: 'men',
    category: 'loafers',
    subcategory: 'footwear',
    sizes: ['40', '41', '42', '43', '44'],
    colors: ['Deep Espresso', 'Tuscan Tan', 'Midnight Black'],
    rating: 4.8,
    reviewCount: 36,
    imageUrl: 'https://images.unsplash.com/photo-1614252369475-531eba835eb1?auto=format&fit=crop&w=1000&q=85',
    description: 'Hand-burnished Italian calfskin leather penny loafers with Blake-stitched leather soles and memory foam cushion insoles.',
    material: 'Italian Nappa Leather',
    occasion: 'wedding, formal, office, dinner',
    styleTags: ['refined', 'classic', 'luxury', 'sleek'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'men-011',
    name: 'Low-Profile Calfskin Court Sneakers',
    price: 5999,
    stock: 20,
    gender: 'men',
    category: 'sneakers',
    subcategory: 'footwear',
    sizes: ['40', '41', '42', '43', '44'],
    colors: ['Off-White Ecru', 'Chalk / Sage'],
    rating: 4.8,
    reviewCount: 64,
    imageUrl: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=1000&q=85',
    description: 'Clean architectural court sneakers made from buttery full-grain leather, Margom rubber cupsoles, and organic cotton laces.',
    material: 'Full-Grain Calfskin',
    occasion: 'casual, weekend, travel',
    styleTags: ['clean', 'minimal', 'modern', 'architectural'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'men-012',
    name: 'Hand-Loomed Cotton Linen Nehru Jacket',
    price: 5499,
    stock: 18,
    gender: 'men',
    category: 'jackets',
    subcategory: 'nehru jacket',
    sizes: ['38', '40', '42', '44'],
    colors: ['Desert Sand', 'Sage Leaf', 'Midnight Navy', 'Obsidian Black'],
    rating: 4.9,
    reviewCount: 33,
    imageUrl: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=1000&q=85',
    description: 'Sleeveless tailored waistcoat cut with a classic mandarin bandh collar from textured handloom cotton and linen.',
    material: 'Handloom Cotton Linen',
    occasion: 'wedding guest, festive, celebration, formal',
    styleTags: ['traditional', 'tailored', 'festive', 'elegant'],
    isNew: true,
    isArchived: false,
  },
  {
    id: 'men-013',
    name: 'Striped Handwoven Khadi Shirt',
    price: 3299,
    stock: 24,
    gender: 'men',
    category: 'shirts',
    subcategory: 'casual shirt',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Indigo Stripe', 'Charcoal Line'],
    rating: 4.7,
    reviewCount: 29,
    imageUrl: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=1000&q=85',
    description: 'Relaxed artisan shirt woven from hand-spun organic yarn with natural dye pinstripes and wooden button closures.',
    material: 'Handwoven Khadi Cotton',
    occasion: 'casual, summer, daytime',
    styleTags: ['artisanal', 'pinstripe', 'breathable'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'men-014',
    name: 'Relaxed Organic Cotton Drawstring Trousers',
    price: 3499,
    stock: 22,
    gender: 'men',
    category: 'chinos',
    subcategory: 'trousers',
    sizes: ['30', '32', '34', '36'],
    colors: ['Oatmeal', 'Washed Olive', 'Obsidian Black'],
    rating: 4.8,
    reviewCount: 41,
    imageUrl: 'https://images.unsplash.com/photo-1517445312882-bc9910d016b7?auto=format&fit=crop&w=1000&q=85',
    description: 'Comfortable tapered lounge trousers tailored from breathable slub cotton with an elasticated waistband and internal drawstring.',
    material: 'Organic Slub Cotton',
    occasion: 'casual, travel, lounge',
    styleTags: ['relaxed', 'drawstring', 'minimal'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'men-015',
    name: 'Indigo Hand-Block Cuban Collar Shirt',
    price: 3199,
    stock: 20,
    gender: 'men',
    category: 'shirts',
    subcategory: 'resort shirt',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Dabu Indigo', 'Natural Ecru'],
    rating: 4.8,
    reviewCount: 37,
    imageUrl: 'https://images.unsplash.com/photo-1598554747436-c9293d6a588f?auto=format&fit=crop&w=1000&q=85',
    description: 'Resort shirt featuring Bagru mud-resist Dabu botanical block prints on lightweight handwoven cotton.',
    material: 'Handloom Cotton with Dabu Print',
    occasion: 'vacation, resort, casual, party',
    styleTags: ['block print', 'resort', 'cuban collar'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'men-016',
    name: 'Textured Handloom Raw Silk Short Kurta',
    price: 5899,
    stock: 16,
    gender: 'men',
    category: 'kurtas',
    subcategory: 'short kurta',
    sizes: ['38', '40', '42', '44'],
    colors: ['Golden Tussar', 'Obsidian Black'],
    rating: 4.9,
    reviewCount: 25,
    imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=1000&q=85',
    description: 'Modern straight-cut short tunic crafted in textured handloom Matka silk with concealed placket detailing.',
    material: 'Matka Raw Silk',
    occasion: 'wedding guest, festive, celebration',
    styleTags: ['textured', 'contemporary ethnic', 'heritage'],
    isNew: true,
    isArchived: false,
  },
  {
    id: 'men-017',
    name: 'Midnight Obsidian Raw Silk Bandhgala',
    price: 8499,
    stock: 15,
    gender: 'men',
    category: 'jackets',
    subcategory: 'bandhgala',
    sizes: ['38', '40', '42', '44'],
    colors: ['Obsidian Black'],
    rating: 4.9,
    reviewCount: 38,
    imageUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1000&q=85',
    description: 'Impeccably tailored black raw silk bandhgala jacket featuring minimalist tonal horn buttons and handcrafted satin lining.',
    material: 'Raw Silk',
    occasion: 'wedding, formal, black tie, reception',
    styleTags: ['monochrome', 'formal', 'sharp', 'luxury'],
    isNew: true,
    isArchived: false,
  },
  {
    id: 'men-018',
    name: 'Chanderi Silk Embroidered Festive Kurta',
    price: 4499,
    stock: 22,
    gender: 'men',
    category: 'kurtas',
    subcategory: 'festive kurta',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Ivory Cream', 'Sage Green', 'Midnight Navy'],
    rating: 4.8,
    reviewCount: 31,
    imageUrl: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=1000&q=85',
    description: 'Lustrous Chanderi silk cotton kurta accented with intricate tonal embroidery along the mandarin collar and placket.',
    material: 'Chanderi Silk Cotton',
    occasion: 'wedding guest, festive, diwali, sangeet',
    styleTags: ['embroidered', 'festive', 'traditional', 'lightweight'],
    isNew: true,
    isArchived: false,
  },
  {
    id: 'men-019',
    name: 'Black Textured Linen Band Collar Shirt',
    price: 2899,
    stock: 30,
    gender: 'men',
    category: 'shirts',
    subcategory: 'formal shirt',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Obsidian Black', 'Chalk White'],
    rating: 4.7,
    reviewCount: 45,
    imageUrl: 'https://images.unsplash.com/photo-1620012253295-c15c429fccf8?auto=format&fit=crop&w=1000&q=85',
    description: 'Understated mandarin collar shirt crafted from heavyweight washed pure linen with natural mother-of-pearl buttons.',
    material: 'Pure Washed Linen',
    occasion: 'formal, office, evening, dinner',
    styleTags: ['minimalist', 'clean', 'band collar', 'breathable'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'men-020',
    name: 'Pure Khadi Cotton Summer Kurta',
    price: 2499,
    stock: 35,
    gender: 'men',
    category: 'kurtas',
    subcategory: 'kurta',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Sage Green', 'Oatmeal Ecru', 'Sky Blue'],
    rating: 4.8,
    reviewCount: 50,
    imageUrl: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=1000&q=85',
    description: 'Light and airy everyday tunic handwoven from fine 80-count organic cotton on village pit looms.',
    material: '80-Count Organic Khadi Cotton',
    occasion: 'casual, summer, daytime, puja',
    styleTags: ['organic', 'breathable', 'comfortable', 'daily wear'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'men-021',
    name: 'Artisanal Khadi Linen Co-ord Trouser Set',
    price: 6999,
    stock: 14,
    gender: 'men',
    category: 'co-ords',
    subcategory: 'co-ord set',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Desert Sand', 'Midnight Black'],
    rating: 4.9,
    reviewCount: 22,
    imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1000&q=85',
    description: 'Modern two-piece menswear co-ord pairing a drop-shoulder popover tunic with matching straight-leg relaxed trousers.',
    material: 'Khadi Linen Cotton',
    occasion: 'destination wedding, resort, vacation, evening',
    styleTags: ['co-ord', 'contemporary', 'architectural', 'relaxed luxury'],
    isNew: true,
    isArchived: false,
  },
  {
    id: 'men-022',
    name: 'Hand-Tailored Fine Wool Blazer',
    price: 9499,
    stock: 12,
    gender: 'men',
    category: 'jackets',
    subcategory: 'blazer',
    sizes: ['38', '40', '42', '44'],
    colors: ['Charcoal Grey', 'Midnight Navy'],
    rating: 4.9,
    reviewCount: 19,
    imageUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1000&q=85',
    description: 'Unstructured single-breasted jacket tailored in lightweight tropical wool with pick-stitch lapels and cupro sleeve lining.',
    material: 'Tropical Merino Wool',
    occasion: 'formal, office, dinner, interview',
    styleTags: ['sartorial', 'unstructured', 'sharp', 'timeless'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'men-023',
    name: 'Archived Handloom Indigo Ikat Shirt',
    price: 2199,
    stock: 8,
    gender: 'men',
    category: 'shirts',
    subcategory: 'casual shirt',
    sizes: ['S', 'M', 'L'],
    colors: ['Indigo Ash'],
    rating: 4.7,
    reviewCount: 24,
    imageUrl: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=1000&q=85',
    description: 'Limited past-season release woven using double-warp Ikat technique by master weavers in Pochampally.',
    material: 'Double-Warp Handloom Cotton',
    occasion: 'casual, weekend',
    styleTags: ['archive', 'ikat', 'heritage'],
    isNew: false,
    isArchived: true,
  },
  {
    id: 'men-024',
    name: 'Archived Vintage Khadi Nehru Vest',
    price: 3199,
    stock: 6,
    gender: 'men',
    category: 'jackets',
    subcategory: 'nehru jacket',
    sizes: ['38', '40', '42'],
    colors: ['Oatmeal Ecru'],
    rating: 4.8,
    reviewCount: 18,
    imageUrl: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=1000&q=85',
    description: 'Archived artisanal waistcoat in hand-spun organic unbleached Khadi with handcrafted bone buttons.',
    material: 'Unbleached Organic Khadi',
    occasion: 'festive, celebration',
    styleTags: ['archive', 'vintage', 'handcrafted'],
    isNew: false,
    isArchived: true,
  },

  // ==================== WOMEN'S COLLECTION (28 items) ====================
  {
    id: 'women-001',
    name: 'Chanderi Silk Fluted Trench Dress',
    price: 8999,
    stock: 10,
    gender: 'women',
    category: 'dresses',
    subcategory: 'trench dress',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Sheer Ivory', 'Rose Quartz', 'Burnished Terracotta', 'Crimson Red'],
    rating: 5.0,
    reviewCount: 38,
    imageUrl: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=1000&q=85',
    description: 'Architectural trench dress cut from hand-spun Chanderi sheer organza featuring mother-of-pearl hardware and fluted sleeves.',
    material: 'Chanderi Silk Organza',
    occasion: 'destination wedding, cocktail, evening gala',
    styleTags: ['architectural', 'fluted', 'sheer', 'couture'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'women-002',
    name: 'Pre-Draped Cashmere Saree Gown',
    price: 9499,
    stock: 8,
    gender: 'women',
    category: 'sarees',
    subcategory: 'saree gown',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Obsidian Black', 'Midnight Navy', 'Emerald Sage'],
    rating: 4.9,
    reviewCount: 29,
    imageUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=85',
    description: 'Effortless evening wear combining fluid grade-A Kashmiri cashmere jersey with pre-stitched sculptural waterfall pleats.',
    material: 'Cashmere Jersey & Silk',
    occasion: 'reception, black tie, red carpet, wedding',
    styleTags: ['pre-draped', 'fluid', 'luxury evening', 'statement'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'women-003',
    name: 'Wild Tussar Silk Pleated Co-ord Set',
    price: 7899,
    stock: 16,
    gender: 'women',
    category: 'contemporary ethnic wear',
    subcategory: 'co-ord set',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Raw Honey Tussar', 'Desert Sand', 'Obsidian Black'],
    rating: 4.8,
    reviewCount: 44,
    imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1000&q=85',
    description: 'Two-piece modern tunic and wide-leg trouser ensemble tailored from unbleached wild Tussar silk with micro-pleated front detailing.',
    material: 'Wild Tussar Silk',
    occasion: 'wedding guest, festive, art opening, dinner',
    styleTags: ['co-ord', 'micro-pleated', 'contemporary', 'artisan luxury'],
    isNew: true,
    isArchived: false,
  },
  {
    id: 'women-004',
    name: 'Tiered Organic Poplin Midi Dress',
    price: 4999,
    stock: 25,
    gender: 'women',
    category: 'dresses',
    subcategory: 'midi dress',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Obsidian Black', 'Cornflower Blue', 'Crisp White', 'Deep Crimson Red'],
    rating: 4.7,
    reviewCount: 53,
    imageUrl: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1000&q=85',
    description: 'Voluminous tiered midi black dress with smocked bodice, delicate puff shoulders, and hidden side seam pockets in certified organic cotton.',
    material: 'Organic Cotton Poplin',
    occasion: 'date night, brunch, casual, dinner, garden wedding',
    styleTags: ['tiered', 'romantic', 'smocked', 'midi silhouette'],
    isNew: true,
    isArchived: false,
  },
  {
    id: 'women-005',
    name: 'Mulberry Silk Wrap Blouse Top',
    price: 5499,
    stock: 20,
    gender: 'women',
    category: 'tops',
    subcategory: 'blouse',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Champagne Pearl', 'Dusty Rose', 'Onyx Black'],
    rating: 4.9,
    reviewCount: 41,
    imageUrl: 'https://images.unsplash.com/photo-1551803091-e20673f15770?auto=format&fit=crop&w=1000&q=85',
    description: 'Bias-cut 22-momme pure mulberry silk wrap blouse with exaggerated elongated cuffs and a fluid self-tie sash.',
    material: '22-Momme Mulberry Silk',
    occasion: 'office, formal, dinner, cocktail',
    styleTags: ['bias-cut', 'wrap blouse', 'flowing', 'silk sheen'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'women-006',
    name: 'Relaxed Belgian Linen Classic Shirt',
    price: 3699,
    stock: 30,
    gender: 'women',
    category: 'shirts',
    subcategory: 'linen shirt',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Pristine White', 'Natural Flax', 'Sage Stripe'],
    rating: 4.8,
    reviewCount: 62,
    imageUrl: 'https://images.unsplash.com/photo-1598554747436-c9293d6a588f?auto=format&fit=crop&w=1000&q=85',
    description: 'Effortlessly oversized linen button-down crafted from stonewashed Master of Linen certified Belgian yarns.',
    material: 'Belgian Stonewashed Linen',
    occasion: 'casual, summer, vacation, everyday',
    styleTags: ['oversized', 'stonewashed', 'relaxed', 'breathable'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'women-007',
    name: 'High-Rise Straight Leg Vintage Jeans',
    price: 4499,
    stock: 24,
    gender: 'women',
    category: 'jeans',
    subcategory: 'jeans',
    sizes: ['26', '28', '30', '32'],
    colors: ['Washed Light Blue', 'Vintage Indigo', 'Bone Ecru'],
    rating: 4.7,
    reviewCount: 71,
    imageUrl: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=1000&q=85',
    description: 'Sculpting high-rise 100% organic cotton rigid denim jeans featuring classic 5-pocket styling and antique silver hardware.',
    material: 'Organic Cotton Rigid Denim',
    occasion: 'casual, weekend, street',
    styleTags: ['vintage wash', 'high rise', 'straight leg'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'women-008',
    name: 'Varanasi Zari Handloom Organza Saree',
    price: 9299,
    stock: 7,
    gender: 'women',
    category: 'sarees',
    subcategory: 'handloom saree',
    sizes: ['Free Size'],
    colors: ['Gold Zari / Sage', 'Crimson / Rose Gold', 'Obsidian / Silver'],
    rating: 5.0,
    reviewCount: 24,
    imageUrl: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1000&q=85',
    description: 'Master artisan handwoven pure silk organza saree with delicate metallic gold zari border motifs, certified handloom provenance.',
    material: 'Pure Silk Organza with Real Zari',
    occasion: 'wedding, festive, reception, royal gathering',
    styleTags: ['heritage', 'handloom', 'zari', 'regal'],
    isNew: true,
    isArchived: false,
  },
  {
    id: 'women-009',
    name: 'Hand-Embroidered Chanderi Kurta Set',
    price: 8499,
    stock: 18,
    gender: 'women',
    category: 'contemporary ethnic wear',
    subcategory: 'kurta set',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Mint Sage', 'Pale Peach', 'Ivory Gold'],
    rating: 4.9,
    reviewCount: 46,
    imageUrl: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1000&q=85',
    description: 'Three-piece ensemble featuring a sheer embroidered Chanderi kurta, tailored cotton silk cigarette pants, and hand-block dupatta.',
    material: 'Chanderi Cotton Silk',
    occasion: 'wedding guest, festive, mehendi, celebration',
    styleTags: ['three-piece', 'embroidered', 'delicate', 'pastel'],
    isNew: true,
    isArchived: false,
  },
  {
    id: 'women-010',
    name: 'Structured Double-Breasted Wool Blazer',
    price: 8999,
    stock: 12,
    gender: 'women',
    category: 'jackets',
    subcategory: 'blazer',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Oatmeal Melange', 'Espresso Charcoal', 'Obsidian Black'],
    rating: 4.9,
    reviewCount: 35,
    imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1000&q=85',
    description: 'Architectural sartorial blazer tailored in fine Australian Merino wool with padded structured shoulders and tortoiseshell buttons.',
    material: 'Fine Australian Merino Wool',
    occasion: 'office, formal, dinner, interview',
    styleTags: ['power tailoring', 'double breasted', 'structured', 'chic'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'women-011',
    name: 'Woven Leather Strappy Resort Sandals',
    price: 4299,
    stock: 22,
    gender: 'women',
    category: 'sandals',
    subcategory: 'footwear',
    sizes: ['36', '37', '38', '39', '40'],
    colors: ['Caramel Tan', 'Natural Bone', 'Espresso Black'],
    rating: 4.8,
    reviewCount: 49,
    imageUrl: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=1000&q=85',
    description: 'Hand-braided vegetable-tanned leather sandals with an ergonomic cushioned footbed and adjustable ankle buckle.',
    material: 'Vegetable-Tanned Leather',
    occasion: 'summer, vacation, resort, casual',
    styleTags: ['braided', 'strappy', 'resort footwear'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'women-012',
    name: 'Minimal Platform Leather Sneakers',
    price: 5499,
    stock: 19,
    gender: 'women',
    category: 'sneakers',
    subcategory: 'footwear',
    sizes: ['36', '37', '38', '39', '40'],
    colors: ['Alabaster White', 'Nude Sage Accent'],
    rating: 4.7,
    reviewCount: 58,
    imageUrl: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=1000&q=85',
    description: 'Contemporary platform court sneakers with soft calf leather upper, subtle gold foil monogramming, and lightweight rubber sole.',
    material: 'Soft Calf Leather',
    occasion: 'casual, weekend, travel',
    styleTags: ['platform', 'clean', 'street luxury'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'women-013',
    name: 'Hand-Block Botanical Cotton Kaftan Dress',
    price: 4299,
    stock: 22,
    gender: 'women',
    category: 'dresses',
    subcategory: 'kaftan dress',
    sizes: ['Free Size'],
    colors: ['Sage Botanical', 'Terracotta Vine', 'Indigo Fern'],
    rating: 4.8,
    reviewCount: 38,
    imageUrl: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=1000&q=85',
    description: 'Flowing resort kaftan dress with drawstring waist cinching, hand-block printed using organic plant-based dyes on pure cotton.',
    material: 'Pure Handloom Cotton',
    occasion: 'resort, beach, pool party, vacation',
    styleTags: ['kaftan', 'bohemian luxury', 'block print'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'women-014',
    name: 'Mulberry Silk Asymmetric Wrap Skirt',
    price: 5999,
    stock: 16,
    gender: 'women',
    category: 'contemporary ethnic wear',
    subcategory: 'skirt',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Dusty Champagne', 'Obsidian Black'],
    rating: 4.9,
    reviewCount: 31,
    imageUrl: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1000&q=85',
    description: 'Sculptural asymmetric midi wrap skirt cut from heavy 30-momme mulberry silk with a clean flat front waistband.',
    material: '30-Momme Mulberry Silk',
    occasion: 'cocktail, dinner, evening, gallery opening',
    styleTags: ['asymmetric', 'wrap skirt', 'fluid silk'],
    isNew: true,
    isArchived: false,
  },
  {
    id: 'women-015',
    name: 'Chanderi Hand-Embroidered Anarkali Kurta',
    price: 7499,
    stock: 15,
    gender: 'women',
    category: 'kurtas',
    subcategory: 'anarkali',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Ivory Gold', 'Blush Peach', 'Royal Emerald'],
    rating: 4.9,
    reviewCount: 42,
    imageUrl: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=1000&q=85',
    description: 'Flared royal silhouette cut from gossamer Chanderi cotton silk with delicate zardozi threadwork on the neckline and hem.',
    material: 'Chanderi Cotton Silk',
    occasion: 'wedding, festive, sangeet, eid, diwali',
    styleTags: ['flared', 'anarkali', 'zardozi', 'heritage'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'women-016',
    name: 'Artisanal Handwoven Linen Trouser',
    price: 3899,
    stock: 20,
    gender: 'women',
    category: 'contemporary ethnic wear',
    subcategory: 'trousers',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Oatmeal Ecru', 'Sage Moss', 'Charcoal'],
    rating: 4.8,
    reviewCount: 29,
    imageUrl: 'https://images.unsplash.com/photo-1508427953056-b00b8d78ebf5?auto=format&fit=crop&w=1000&q=85',
    description: 'High-waisted wide-leg trousers tailored from stonewashed organic European linen with slash front pockets.',
    material: 'Organic European Linen',
    occasion: 'office, resort, daytime, casual',
    styleTags: ['wide leg', 'high waisted', 'breathable'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'women-017',
    name: 'Hand-Pleated Organic Cotton Maxi Dress',
    price: 4699,
    stock: 24,
    gender: 'women',
    category: 'dresses',
    subcategory: 'maxi dress',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Midnight Obsidian', 'Warm Sand', 'Emerald'],
    rating: 4.8,
    reviewCount: 47,
    imageUrl: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=1000&q=85',
    description: 'Graceful tiered maxi black dress with sunburst micro-pleats and a flattering halter tie neckline.',
    material: 'Organic Handloom Cotton',
    occasion: 'evening, vacation, wedding guest, summer dinner',
    styleTags: ['halter neck', 'pleated maxi', 'sunburst pleats'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'women-018',
    name: 'Wild Tussar Silk Minimalist Wrap Dress',
    price: 5499,
    stock: 18,
    gender: 'women',
    category: 'dresses',
    subcategory: 'wrap dress',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Obsidian Black', 'Raw Honey', 'Deep Forest'],
    rating: 4.9,
    reviewCount: 36,
    imageUrl: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1000&q=85',
    description: 'Sleek black wrap dress tailored in textured wild Tussar silk with deep V-neckline and internal waist ribbon cinch.',
    material: 'Wild Tussar Silk',
    occasion: 'formal, cocktail, date night, dinner',
    styleTags: ['wrap silhouette', 'little black dress', 'minimal luxury'],
    isNew: true,
    isArchived: false,
  },
  {
    id: 'women-019',
    name: 'Structured Formal Blazer Dress in Black',
    price: 6999,
    stock: 15,
    gender: 'women',
    category: 'dresses',
    subcategory: 'blazer dress',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Obsidian Black'],
    rating: 4.9,
    reviewCount: 40,
    imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1000&q=85',
    description: 'Impeccably tailored double-breasted tuxedo dress in fine stretch wool blend with peak satin lapels.',
    material: 'Wool Silk Blend',
    occasion: 'formal, evening, corporate gala, cocktail',
    styleTags: ['tuxedo dress', 'black formal dress', 'sharp tailoring'],
    isNew: true,
    isArchived: false,
  },
  {
    id: 'women-020',
    name: 'Summer Linen Slip Midi Dress',
    price: 3899,
    stock: 26,
    gender: 'women',
    category: 'dresses',
    subcategory: 'slip dress',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Ecru Cream', 'Washed Olive', 'Obsidian Black'],
    rating: 4.8,
    reviewCount: 52,
    imageUrl: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=1000&q=85',
    description: 'Minimalist slip dress cut on the bias from airy washed linen with delicate adjustable spaghetti straps.',
    material: '100% Washed Linen',
    occasion: 'summer, vacation, beach, casual dinner',
    styleTags: ['slip dress', 'bias cut', 'effortless'],
    isNew: true,
    isArchived: false,
  },
  {
    id: 'women-021',
    name: 'Organic Cotton Summer Sundress',
    price: 2899,
    stock: 32,
    gender: 'women',
    category: 'dresses',
    subcategory: 'sundress',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Crisp White', 'Cornflower Blue', 'Blush'],
    rating: 4.7,
    reviewCount: 60,
    imageUrl: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=1000&q=85',
    description: 'Sweetheart neckline sundress with a flared A-line skirt and side pocket construction in light organic cotton.',
    material: 'Organic Voile Cotton',
    occasion: 'summer, casual, daytime, vacation',
    styleTags: ['sundress', 'sweetheart', 'breezy'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'women-022',
    name: 'Chanderi Handloom Festive Saree in Crimson',
    price: 8999,
    stock: 12,
    gender: 'women',
    category: 'sarees',
    subcategory: 'chanderi saree',
    sizes: ['Free Size'],
    colors: ['Crimson Red', 'Emerald Green', 'Royal Navy'],
    rating: 4.9,
    reviewCount: 34,
    imageUrl: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1000&q=85',
    description: 'Festive Chanderi silk saree with handcrafted gold zari butti work and woven pallu details.',
    material: 'Chanderi Pattu Silk',
    occasion: 'wedding, festive, diwali, karwa chauth, puja',
    styleTags: ['festive saree', 'traditional', 'zari butti'],
    isNew: true,
    isArchived: false,
  },
  {
    id: 'women-023',
    name: 'Mulberry Silk Printed Saree in Indigo',
    price: 6499,
    stock: 14,
    gender: 'women',
    category: 'sarees',
    subcategory: 'silk saree',
    sizes: ['Free Size'],
    colors: ['Indigo Blue', 'Teal Green'],
    rating: 4.8,
    reviewCount: 28,
    imageUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=85',
    description: 'Featherlight pure mulberry silk saree adorned with modern geometric discharge block prints.',
    material: 'Pure Mulberry Silk',
    occasion: 'festive, farewell, dinner, cocktail',
    styleTags: ['geometric print', 'lightweight saree', 'indigo'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'women-024',
    name: 'Chanderi Silk Flared Kurta Set in Peach',
    price: 6499,
    stock: 17,
    gender: 'women',
    category: 'kurtas',
    subcategory: 'kurta set',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Blush Peach', 'Mint Sage'],
    rating: 4.8,
    reviewCount: 39,
    imageUrl: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1000&q=85',
    description: 'Charming two-piece A-line Chanderi kurta with tonal gota patti work and coordinated straight palazzo pants.',
    material: 'Chanderi Silk Cotton',
    occasion: 'wedding guest, festive, haldi, celebration',
    styleTags: ['gota patti', 'festive kurta', 'pastel'],
    isNew: true,
    isArchived: false,
  },
  {
    id: 'women-025',
    name: 'Handloom Cotton Everyday Straight Kurta',
    price: 2499,
    stock: 30,
    gender: 'women',
    category: 'kurtas',
    subcategory: 'daily kurta',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Indigo Blue', 'Ivory', 'Terracotta'],
    rating: 4.7,
    reviewCount: 48,
    imageUrl: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=1000&q=85',
    description: 'Breathable straight-fit daily wear kurta with subtle side slits and wooden loop buttons.',
    material: '100% Handloom Cotton',
    occasion: 'office, casual, everyday',
    styleTags: ['daily ethnic', 'comfort', 'straight fit'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'women-026',
    name: 'Mulberry Silk Tiered Ruffle Blouse',
    price: 3499,
    stock: 22,
    gender: 'women',
    category: 'tops',
    subcategory: 'blouse',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Ivory Cream', 'Dusty Rose', 'Midnight Black'],
    rating: 4.8,
    reviewCount: 33,
    imageUrl: 'https://images.unsplash.com/photo-1551803091-e20673f15770?auto=format&fit=crop&w=1000&q=85',
    description: 'Delicate ruffle collar silk top featuring romantic smocked cuffs and a loose flowing drape.',
    material: 'Mulberry Silk Georgette',
    occasion: 'office, date night, dinner',
    styleTags: ['romantic', 'ruffle blouse', 'feminine'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'women-027',
    name: 'Archived Hand-Painted Kalamkari Silk Dress',
    price: 4999,
    stock: 5,
    gender: 'women',
    category: 'dresses',
    subcategory: 'maxi dress',
    sizes: ['S', 'M', 'L'],
    colors: ['Natural Indigo / Madder'],
    rating: 4.9,
    reviewCount: 17,
    imageUrl: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=1000&q=85',
    description: 'Collector edition maxi dress handcrafted with Srikalahasti pen Kalamkari natural vegetable dye artwork.',
    material: 'Handloom Silk with Pen Kalamkari',
    occasion: 'art gala, celebration',
    styleTags: ['archive', 'kalamkari', 'heritage art'],
    isNew: false,
    isArchived: true,
  },
  {
    id: 'women-028',
    name: 'Archived Raw Silk Brocade Peplum Top',
    price: 3899,
    stock: 4,
    gender: 'women',
    category: 'tops',
    subcategory: 'blouse',
    sizes: ['XS', 'S', 'M'],
    colors: ['Vintage Gold / Ecru'],
    rating: 4.8,
    reviewCount: 15,
    imageUrl: 'https://images.unsplash.com/photo-1551803091-e20673f15770?auto=format&fit=crop&w=1000&q=85',
    description: 'Archived structured peplum blouse tailored from handloom Banarasi vintage zari brocade.',
    material: 'Banarasi Brocade Silk',
    occasion: 'festive, wedding guest',
    styleTags: ['archive', 'brocade', 'peplum'],
    isNew: false,
    isArchived: true,
  },

  // ==================== UNISEX & ACCESSORIES COLLECTION (18 items) ====================
  {
    id: 'uni-001',
    name: 'Full-Grain Leather Atelier Tote Bag',
    price: 7999,
    stock: 20,
    gender: 'unisex',
    category: 'tote bags',
    subcategory: 'leather bag',
    sizes: ['One Size'],
    colors: ['Vintage Saddle Tan', 'Espresso Black'],
    rating: 4.9,
    reviewCount: 73,
    imageUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=1000&q=85',
    description: 'Spacious everyday architectural tote bag cut from unlined full-grain vegetable-tanned leather with reinforced shoulder straps and interior laptop sleeve.',
    material: 'Vegetable-Tanned Full-Grain Leather',
    occasion: 'work, travel, everyday',
    styleTags: ['tote bag', 'leather goods', 'timeless'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'uni-002',
    name: 'Organic Canvas & Leather Weekender Tote',
    price: 4999,
    stock: 25,
    gender: 'unisex',
    category: 'tote bags',
    subcategory: 'canvas tote',
    sizes: ['One Size'],
    colors: ['Ecru / Tan Leather', 'Olive / Black Leather'],
    rating: 4.8,
    reviewCount: 51,
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1000&q=85',
    description: 'Heavyweight 18oz water-repellent organic cotton canvas tote featuring full-grain harness leather handles and brass YKK hardware.',
    material: '18oz Organic Canvas & Harness Leather',
    occasion: 'weekend travel, resort, market',
    styleTags: ['weekender', 'durable', 'canvas tote'],
    isNew: true,
    isArchived: false,
  },
  {
    id: 'uni-003',
    name: 'Changthangi Cashmere Draped Overshirt',
    price: 8499,
    stock: 11,
    gender: 'unisex',
    category: 'overshirts',
    subcategory: 'shacket',
    sizes: ['S/M', 'L/XL'],
    colors: ['Natural Pashm Ecru', 'Charcoal Heather', 'Dusty Sage'],
    rating: 5.0,
    reviewCount: 32,
    imageUrl: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1000&q=85',
    description: 'Featherlight oversized shacket spun from Grade-A Changthangi mountain goat fleece with horn buttons and patch front pockets.',
    material: 'Grade-A Changthangi Cashmere',
    occasion: 'winter, travel, evening',
    styleTags: ['pashm', 'cashmere overshirt', 'unisex luxury'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'uni-004',
    name: 'Heavy Twill Boxy Chore Overshirt',
    price: 4499,
    stock: 30,
    gender: 'unisex',
    category: 'overshirts',
    subcategory: 'chore jacket',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['French Worker Blue', 'Sage Khaki', 'Washed Bone'],
    rating: 4.8,
    reviewCount: 65,
    imageUrl: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=1000&q=85',
    description: 'Classic utilitarian workwear overshirt crafted from 100% organic heavy cotton twill with 3 patch utility pockets and double-needle stitching.',
    material: 'Heavy Organic Cotton Twill',
    occasion: 'casual, weekend, layering',
    styleTags: ['chore jacket', 'workwear', 'boxy fit'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'uni-005',
    name: 'Pure Pashmina Handwoven Fringe Shawl',
    price: 9999,
    stock: 14,
    gender: 'unisex',
    category: 'accessories',
    subcategory: 'shawl',
    sizes: ['200 x 70 cm'],
    colors: ['Natural Camel', 'Ecru Cream', 'Muted Sage', 'Obsidian Black'],
    rating: 4.9,
    reviewCount: 43,
    imageUrl: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&w=1000&q=85',
    description: 'Authentic GI-certified hand-spun Kashmiri Pashmina wrap with delicate eyelash fringe edges, woven on wooden handlooms in Srinagar.',
    material: 'GI-Certified Kashmiri Pashmina',
    occasion: 'wedding, winter formal, travel, evening',
    styleTags: ['pashmina wrap', 'fringe shawl', 'warmth luxury'],
    isNew: true,
    isArchived: false,
  },
  {
    id: 'uni-006',
    name: 'Solid Brass & Saddle Leather Minimal Belt',
    price: 2499,
    stock: 35,
    gender: 'unisex',
    category: 'accessories',
    subcategory: 'belt',
    sizes: ['30', '32', '34', '36', '38'],
    colors: ['Cognac Tan', 'Pitch Black'],
    rating: 4.7,
    reviewCount: 88,
    imageUrl: 'https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=1000&q=85',
    description: '3.5cm full-grain English bridle leather belt with solid sand-cast brass buckle that develops a rich natural patina over time.',
    material: 'Full-Grain Bridle Leather & Sand-Cast Brass',
    occasion: 'office, formal, casual',
    styleTags: ['leather belt', 'solid brass', 'patina'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'uni-007',
    name: 'Monochrome Minimal Raw Canvas Sneakers',
    price: 3999,
    stock: 28,
    gender: 'unisex',
    category: 'minimal sneakers',
    subcategory: 'footwear',
    sizes: ['37', '38', '39', '40', '41', '42', '43'],
    colors: ['Unbleached Ecru', 'Charcoal Canvas'],
    rating: 4.8,
    reviewCount: 57,
    imageUrl: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=1000&q=85',
    description: 'Vulcanized low-top sneakers crafted from durable unbleached organic duck canvas and natural tree-sap gum rubber soles.',
    material: 'Organic Duck Canvas & Gum Rubber',
    occasion: 'casual, weekend, city walk',
    styleTags: ['vulcanized', 'canvas sneakers', 'monochrome'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'uni-008',
    name: 'Hand-Spun Khadi Silk & Wool Stole',
    price: 2899,
    stock: 30,
    gender: 'unisex',
    category: 'accessories',
    subcategory: 'stole',
    sizes: ['Free Size'],
    colors: ['Oatmeal Grey', 'Sage Mist', 'Charcoal Black'],
    rating: 4.9,
    reviewCount: 54,
    imageUrl: 'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?auto=format&fit=crop&w=1000&q=85',
    description: 'Lightweight heritage stole handwoven from a blend of natural mulberry silk and Merino wool with micro-fringed hems.',
    material: 'Mulberry Silk & Merino Wool',
    occasion: 'wedding guest, festive, winter layering, evening',
    styleTags: ['silk stole', 'layering wrap', 'handloom accessory'],
    isNew: true,
    isArchived: false,
  },
  {
    id: 'uni-009',
    name: 'Full-Grain Nappa Leather Minimal Zip Wallet',
    price: 2199,
    stock: 40,
    gender: 'unisex',
    category: 'accessories',
    subcategory: 'wallet',
    sizes: ['One Size'],
    colors: ['Espresso Black', 'Caramel Tan'],
    rating: 4.8,
    reviewCount: 61,
    imageUrl: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=1000&q=85',
    description: 'Slim compact zip-around wallet crafted in buttery full-grain Italian Nappa leather with Japanese YKK Excella hardware.',
    material: 'Italian Nappa Leather',
    occasion: 'everyday, travel',
    styleTags: ['zip wallet', 'leather wallet', 'compact'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'uni-010',
    name: 'Hand-Block Printed Botanical Cotton Scarf',
    price: 1699,
    stock: 35,
    gender: 'unisex',
    category: 'accessories',
    subcategory: 'scarf',
    sizes: ['Free Size'],
    colors: ['Natural Indigo', 'Madder Red', 'Sage Botanical'],
    rating: 4.7,
    reviewCount: 48,
    imageUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1000&q=85',
    description: 'Handcrafted square bandanna scarf block-printed by 4th-generation artisan printers in Bagru using natural herbal dyes.',
    material: 'Fine Mulmul Cotton with Plant Dyes',
    occasion: 'casual, summer, accessory styling',
    styleTags: ['bandanna', 'block print scarf', 'herbal dyes'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'uni-011',
    name: 'Organic Bamboo Silk Everyday Tee',
    price: 1899,
    stock: 45,
    gender: 'unisex',
    category: 't-shirts',
    subcategory: 't-shirt',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Natural Chalk', 'Obsidian Black', 'Sage Green'],
    rating: 4.8,
    reviewCount: 77,
    imageUrl: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=1000&q=85',
    description: 'Hypoallergenic, ultra-breathable crewneck t-shirt spun from sustainable organic bamboo viscose and silk fibers.',
    material: 'Organic Bamboo & Silk Viscose',
    occasion: 'everyday, lounge, casual',
    styleTags: ['bamboo silk', 'soft tee', 'sustainable'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'uni-012',
    name: 'Minimal Vegetable-Tanned Leather Cardholder',
    price: 1499,
    stock: 50,
    gender: 'unisex',
    category: 'accessories',
    subcategory: 'cardholder',
    sizes: ['One Size'],
    colors: ['Saddle Tan', 'Pitch Black', 'Forest Green'],
    rating: 4.9,
    reviewCount: 82,
    imageUrl: 'https://images.unsplash.com/photo-1563903530-0879fe659690?auto=format&fit=crop&w=1000&q=85',
    description: 'Hand-burnished 4-slot minimalist cardholder cut from vegetable-tanned Tuscan leather with hand-waxed saddle stitching.',
    material: 'Tuscan Vegetable-Tanned Leather',
    occasion: 'everyday, work, gifting',
    styleTags: ['cardholder', 'slim', 'hand stitched'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'uni-013',
    name: 'Banarasi Gold Zari Brocade Stole',
    price: 1999,
    stock: 25,
    gender: 'unisex',
    category: 'accessories',
    subcategory: 'stole',
    sizes: ['Free Size'],
    colors: ['Vintage Gold / Cream', 'Crimson / Gold'],
    rating: 4.8,
    reviewCount: 39,
    imageUrl: 'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?auto=format&fit=crop&w=1000&q=85',
    description: 'Exquisite handloom festive stole featuring Banarasi zari motifs along the border, ideal for pairing with bandhgalas and kurtas.',
    material: 'Silk Cotton with Gold Zari',
    occasion: 'wedding guest, festive, reception',
    styleTags: ['banarasi stole', 'gold accent', 'festive wrap'],
    isNew: true,
    isArchived: false,
  },
  {
    id: 'uni-014',
    name: 'Handcrafted Heritage Leather Mojaris',
    price: 3499,
    stock: 20,
    gender: 'unisex',
    category: 'sandals',
    subcategory: 'footwear',
    sizes: ['38', '39', '40', '41', '42', '43'],
    colors: ['Caramel Tan', 'Obsidian Black'],
    rating: 4.8,
    reviewCount: 31,
    imageUrl: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=1000&q=85',
    description: 'Traditional Jodhpur leather juttis crafted by master cobblers with cushioned memory insoles and hand-stitched soles.',
    material: 'Pure Hand-Tanned Leather',
    occasion: 'wedding, festive, traditional celebration',
    styleTags: ['mojaris', 'juttis', 'heritage footwear'],
    isNew: true,
    isArchived: false,
  },
  {
    id: 'uni-015',
    name: 'Chanderi Hand-Printed Botanical Dupatta',
    price: 1499,
    stock: 35,
    gender: 'unisex',
    category: 'accessories',
    subcategory: 'stole',
    sizes: ['Free Size'],
    colors: ['Sage Green', 'Indigo Ash', 'Rose Quartz'],
    rating: 4.7,
    reviewCount: 42,
    imageUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1000&q=85',
    description: 'Featherlight sheer Chanderi stole with delicate gold foil borders and organic block printed botanical vines.',
    material: 'Chanderi Cotton Silk',
    occasion: 'wedding guest, festive, summer styling',
    styleTags: ['chanderi stole', 'botanical print', 'lightweight'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'uni-016',
    name: 'Slim Bridle Leather Dress Belt in Black',
    price: 1899,
    stock: 30,
    gender: 'unisex',
    category: 'accessories',
    subcategory: 'belt',
    sizes: ['30', '32', '34', '36', '38'],
    colors: ['Obsidian Black'],
    rating: 4.8,
    reviewCount: 47,
    imageUrl: 'https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=1000&q=85',
    description: 'Slim 3.0cm polished dress belt with bevelled edges and silver satin buckle for tailored formal trousers.',
    material: 'English Bridle Leather',
    occasion: 'formal, office, black tie',
    styleTags: ['dress belt', 'black leather', 'formal accessory'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'uni-017',
    name: 'Foldover Vegetable-Tanned Card Wallet',
    price: 1299,
    stock: 40,
    gender: 'unisex',
    category: 'accessories',
    subcategory: 'wallet',
    sizes: ['One Size'],
    colors: ['Saddle Tan', 'Espresso Black'],
    rating: 4.8,
    reviewCount: 55,
    imageUrl: 'https://images.unsplash.com/photo-1563903530-0879fe659690?auto=format&fit=crop&w=1000&q=85',
    description: 'Ultra-thin bifold cardholder with magnetic closure and dual quick-access exterior slots.',
    material: 'Full-Grain Tuscan Leather',
    occasion: 'everyday, work, gifting',
    styleTags: ['card wallet', 'minimal', 'bifold'],
    isNew: false,
    isArchived: false,
  },
  {
    id: 'uni-018',
    name: 'Archived Hand-Knotted Tussar Silk Fringe Stole',
    price: 1899,
    stock: 5,
    gender: 'unisex',
    category: 'accessories',
    subcategory: 'stole',
    sizes: ['Free Size'],
    colors: ['Raw Honey Tussar'],
    rating: 4.8,
    reviewCount: 20,
    imageUrl: 'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?auto=format&fit=crop&w=1000&q=85',
    description: 'Past-season natural unbleached Tussar silk stole with artisan hand-knotted fringe ends.',
    material: 'Unbleached Wild Tussar Silk',
    occasion: 'celebration, evening',
    styleTags: ['archive', 'tussar stole', 'hand knotted'],
    isNew: false,
    isArchived: true,
  },
];
